server:
  port: 8280
  servlet:
    context-path: /demo/discovery

spring:
  application:
    name: discovery
  cloud:
    discovery:
      blocking:
        enabled: true
      reactive:
        enabled: false  
  freemarker:
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false
        
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://127.0.0.1:8280/demo/discovery/eureka
    
management:
  endpoints:
    enabled-by-default: true
    web.exposure.include: "*"
    jmx.exposure.exclude: "*"
  endpoint:
    health:
      show-details: always
      
